In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2,  1, 3, 3, 1, 2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [3]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [4]:
X_st = X.copy()
X_st[2, :] = calc_std_feat(X[2, :])

In [73]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(np.where(y_pred==0.0, np.ones(len(y_pred)), y_pred)) + (1.0 - y) * np.log(1.0 - np.where(y_pred==1.0, np.zeros(len(y_pred)), y_pred)))
    err = np.sum(err)
    return err

In [7]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [8]:
z = np.linspace(-10, 10, 101)

In [9]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [86]:
W = eval_model(X_st, y, iterations=5000, alpha=1e-4)

500 [ 0.47822106 -0.20918419  0.64605995  1.49531432] 1.0559639161585663
1000 [ 0.46074241 -0.27647603  0.64395686  1.46891696] 0.945214871179169
1500 [ 0.44435675 -0.33951515  0.64152026  1.44406912] 0.8478360281905125
2000 [ 0.42913461 -0.39751872  0.63899625  1.42106251] 0.7651177745022372
2500 [ 0.41513888 -0.44956784  0.63671032  1.40023024] 0.6981293270105478
3000 [ 0.40240136 -0.49488241  0.63498247  1.38184975] 0.6468813805442176
3500 [ 0.39088925 -0.53321212  0.63401986  1.36601535] 0.6097021563515638
4000 [ 0.38049869 -0.56497213  0.63387116  1.35259671] 0.5836774145473647
4500 [ 0.37108342 -0.59102182  0.63446603  1.3413119 ] 0.5657147376221167
5000 [ 0.36249064 -0.61234585  0.63568321  1.33183158] 0.5532737788236778


## Д/з

1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [81]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(np.where(y_pred==0.0, np.ones(len(y_pred)), y_pred)) + (1.0 - y) * np.log(1.0 - np.where(y_pred==1.0, np.zeros(len(y_pred)), y_pred)))
    err = np.sum(err)
    return err

2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [89]:
W = eval_model(X_st, y, iterations=1000, alpha=2000)

100 [-6357.77170631 -2101.44828591   213.69195045  8269.67245078] 5.440557802491661
200 [-10957.79690882  -1501.47348841  -2230.10185238  11069.64724828] 34.70601776610128
300 [-11796.37643273  -1701.47348841  -2608.01432146  10831.06772436] 3.511047008747956e-12
400 [-11796.37643344  -1701.47348841  -2608.01432121  10831.06772365] 3.511047008747956e-12
500 [-11796.37643414  -1701.47348841  -2608.01432096  10831.06772295] 3.511047008747956e-12
600 [-11796.37643484  -1701.47348841  -2608.0143207   10831.06772225] 3.511035906517709e-12
700 [-11796.37643554  -1701.47348841  -2608.01432045  10831.06772155] 3.511035906517709e-12
800 [-11796.37643625  -1701.47348841  -2608.0143202   10831.06772085] 3.511024804287463e-12
900 [-11796.37643695  -1701.47348841  -2608.01431994  10831.06772014] 3.511024804287463e-12
1000 [-11796.37643765  -1701.47348841  -2608.01431969  10831.06771944] 3.511013702057216e-12


3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [84]:
def calc_predict_proba(W, X):
    
    y_pred_proba = sigmoid(np.dot(W.T, X))
    
    return y_pred_proba

In [90]:
calc_predict_proba(W, X_st)

array([2.28965313e-49, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 3.51101538e-11, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00])

4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [111]:
def calc_pred(W, X):
    #     За порог отнесения к тому или иному классу примем вероятность 0.5
    y_pred = np.sign(sigmoid(np.dot(W.T, X))-0.5)
    y_pred = np.maximum(y_pred, np.zeros(len(y_pred)))
    
    return y_pred

In [114]:
y_pred = calc_pred(W, X_st)
y_pred

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [115]:
Accuracy = np.mean([y_pred == y])*100
Accuracy

100.0

In [134]:
err_matrix = np.array([[np.sum((y_pred == 1) & (y==1)), np.sum((y_pred == 1) & (y==-1))],
        [np.sum((y_pred == -1) & (y==1)), np.sum((y_pred == -1) & (y==-1))]])
err_matrix

array([[5, 0],
       [0, 0]])

In [135]:
precision = err_matrix[0][0]/(err_matrix[0][0] + err_matrix[0][1])
precision

1.0

In [136]:
recall = err_matrix[0][0]/(err_matrix[0][0] + err_matrix[1][0])
recall

1.0

In [137]:
F = 2 * precision * recall / (precision + recall)
F

1.0

6. Могла ли модель переобучиться? Почему?

Да, как и любая линейная модель. В частности, это произошло во втором задании.